### ISSUE TITLE
What does fsm mean?

### ISSUE THREAD

**Issue by chughes87** [notpeter/playdate-friction#1]
Hey, I was reading through the code and I'm curious what `fsm` stands for?

https://github.com/notpeter/playdate-friction/blob/f210eb7e5498f121aa23214d14dc0ee19a8532b6/src/gimme.lua#L48

**Comment by notpeter** [comment]
Finite state machine. If you look in the update function you’ll see it calls fsm() every frame. The fsm variable points to one (and only one) function depending on which state the game is in (tripod rotation, shooting, gameover, etc).

**Comment by chughes87** [comment]
Ok thank you!
